import {Component} from '@angular/core';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  dataString:any[] = [
    {
      'Sl no': 1,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11102DG351AA2',
      'ID no.': 6641280130013,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40969,
      In: 1000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 550,
      'L-Time-Lag tr (@6 x IR)': '14 Sec @I2t',
      Memory: 'ON',
      'Short Time Isd': 2,
      'Short Time Current Isd': 2000,
      'Short Time Delay tsd (@12 x In)': '20 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'TOP R Phase - Defective',
      'Contact Pressure': 'OK',
      'Pole Set': 'R Phase - Defective',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'Yes',
      'CRM Values - Before':
        '1. R Phase - \r\n2. Y Phase - \r\n3. B Phase - \r\n4. N Phase -',
      'CRM Values - After':
        '1. R Phase - \r\n2. Y Phase - \r\n3. B Phase - \r\n4. N Phase -',
      'Timing Testing Done': 'Yes',
      __EMPTY:
        '1. R Phase - \r\n2. Y Phase - \r\n3. B Phase - \r\n4. N Phase -',
      'Mandatory Spares':
        'Lamination Contacts 1,Lamination Contacts 2, Lamination Contacts 3, Lamination Contacts 4, Lamination Contacts 5',
      'Recommended Spares': 'Spring Charging Motor',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'R phase over temperature observed, to be rectified',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 2,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11082DG351AA2',
      'ID no.': 6641280130019,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40970,
      In: 800,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 440.00000000000006,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'B=300A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Not Available',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Timing Testing Done': 'No',
      'Mandatory Spares': 'Pole Assembly',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 3,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12252DG351AA2',
      'ID no.': 6641280205024,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40971,
      In: 2500,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1375,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 6250,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'B=300A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'TOP N Phase - Defective',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 4,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12402FG451AA2',
      'ID no.': 6641280312004,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40972,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 10000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'D=900A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': '2 X',
      'CT Test': 'L1 Defective',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - Not OK',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 5,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12202EG351AA2',
      'ID no.': 6641320514022,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40973,
      In: 2000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1100,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 5000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 6,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12202EG351AA2',
      'ID no.': 6641280130005,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40974,
      In: 2000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1100,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 5000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 7,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12402FG451AA2',
      'ID no.': 6641280312005,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40975,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 10000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 8,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12252DG351AA2',
      'ID no.': 6641280205023,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40976,
      In: 2500,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1375,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 6250,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 9,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11102DG351AA2',
      'ID no.': 6641280131001,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40977,
      In: 1000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 550,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2500,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'One or More Defective',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 10,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12252DG351AA2',
      'ID no.': 6641280124004,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40978,
      In: 2500,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1375,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 6250,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'TOP B B Phase - Defective',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 11,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11082DG351AA2',
      'ID no.': 6641280306013,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40979,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 10000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'B Phase - Defective',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 12,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12402FG451AA2',
      'ID no.': 6641232051402,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40980,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 10000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 13,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11082DG351AA2',
      'ID no.': 6641320505019,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40981,
      In: 800,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 440.00000000000006,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 14,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11082DG351AA2',
      'ID no.': 6641320505017,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40982,
      In: 800,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 440.00000000000006,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 15,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12402FG451AA2',
      'ID no.': 6641320514023,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40983,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 7,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'BOTTOM R Phase - Defective',
      'Contact Pressure': 'OK',
      'Pole Set': 'B Phase - Defective',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 16,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11102DG351AA2',
      'ID no.': 6641328013004,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40984,
      In: 1000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 550,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2500,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 17,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12202EG351AA2',
      'ID no.': 6641280131020,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40985,
      In: 2000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1100,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 5000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 18,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11102DG351AA2',
      'ID no.': 6641320505011,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40986,
      In: 1000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 550,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2500,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 19,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL11102DG351AA2',
      'ID no.': 6641320505010,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40987,
      In: 1000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 550,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 2500,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 20,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12402FG451AA2',
      'ID no.': 6641280312007,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40988,
      In: 4000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 2200,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 10000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
    {
      'Sl no': 21,
      'Date - DD.MM.YYYY': '01.03.2022',
      Service: 'OTC',
      'Customer ': 'PharmaZell (Vizag)Private Limited,',
      Location: 'Vizag',
      'Contact Person': 'Mr. KVV Subba Rao',
      Mobile: 9704123462,
      'E-Mail ': 'subbarao@pharmazell.com',
      Panel: 'PMCC',
      'Feeder Name': 'Incomer ',
      Model: '3WL',
      MLFB: '3WL12202EG351AA2',
      'ID no.': 6641340926024,
      'Breaker Rating': '1250A',
      'Size ': 1,
      Pole: '3 Pole',
      Breaker: 'Drawout ',
      ETU: 'ETU45B',
      'Last Serviced on - MM/YYYY': 40989,
      In: 2000,
      'L-Tripping IR =': 0.55,
      'Long Time Current ': 1100,
      'L-Time-Lag tr (@6 x IR)': '2 Sec @I4t',
      Memory: 'ON',
      'Short Time Isd': 2.5,
      'Short Time Current Isd': 5000,
      'Short Time Delay tsd (@12 x In)': '100 ms',
      'I-tripping Ii =': '4 x In',
      'N-Tripping IN': '0.5 x In',
      'I N': 'ON',
      'G-CT': 'IG',
      'G-Tripping Ig': 'A= 100A',
      'G-Alarm Ig': 'A= 100A',
      'Time Delay tg TRIP': '0.3 Sec (I2t)',
      'ETU STATUS': 'OK',
      'CT Test': 'ALL OK',
      'Function Test': 'L-S-I-N-G-OK',
      'Mechanical reclosing lockout': 'OK',
      'Trip Unit (N+G)': 'ACTIVE ',
      'Mechanical Interlock': 'Castel lock - OK -A',
      'Racking Handle': 'OK',
      'Position Indicator': 'Not OK',
      'Contact Erosion Indicator': 'All Phases - OK',
      'Arc Chutes': 'All Phases - OK',
      Shutter: 'OK',
      'Lamination Contacts': 'All Phases - OK',
      'Guide Frame Terminals': 'All Phases - OK',
      'Contact Pressure': 'OK',
      'Pole Set': 'OK',
      Lubrication: 'Completed ',
      'Spring Charging - Manual': 'OK',
      'Spring Charging - Motor': '220V AC/DC -OK',
      Undervoltage: 'Not Available',
      'Closing Coil': '220V AC/DC -OK',
      'Shunt Coil': '220V AC/DC -OK',
      'Ready to Close Interlock': 'OK',
      'Breaker Operations - Manual': 'ON & OFF - OK',
      'Breaker Operations - Electrical': 'ON & OFF - OK',
      'CRM Testing Done': 'No',
      'Mandatory Spares': 'Shutter ',
      'Recommended Spares': 'Coils',
      Comments: 'Breaker Service and testing Completed - OK',
      'Open Points': 'Safety Shutter Broken',
      'Overall Breaker Healthiness': 0.55,
      'Tested By': 'D Satyanarayana',
      'Contact No: ': 9985623105,
      'Reviewed By': 'M Santhosh',
      'Contact No: _1': 9849343545,
    },
  ];

  onFileChange(ev:any) {
    let workBook:any = null;
    let jsonData = null;
    const reader = new FileReader();
    const file = ev.target.files[0];
    reader.onload = (event) => {
      const data = reader.result;
      debugger;
      workBook = XLSX.read(data, {type: 'binary'});
      jsonData = workBook.SheetNames.reduce((initial:any, name:any) => {
        const sheet = workBook.Sheets[name];
        initial[name] = XLSX.utils.sheet_to_json(sheet);
        return initial;
      }, {});
      const dataString = JSON.stringify(jsonData);
      this.dataString = jsonData[Object.keys(jsonData)[0]];
    };
    reader.readAsBinaryString(file);
  }
}
